{
 "title": "Celery Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Celery Task Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "celery_task_duration_sum/ celery_task_duration_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=~\"^(cpu|io)$\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Workers Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 0 },
   "targets": [
    { "expr": "celery_worker_count", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "IO Tasks Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (event) (celery_task_event{name=\"io_task\"})",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "CPU Tasks Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "sum by (event) (celery_task_event{name=\"cpu_task\"})",
     "legendFormat": "{{event}} "
    }
   ]
  },
  {
   "title": "CPU Task Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "celery_task_duration{name=\"cpu_task\"}",
     "legendFormat": "{{name}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Successful Tasks Rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(celery_task_event{state=\"SUCCESS\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failed Task Rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(celery_task_event{state=\"FAILURE\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IOTask Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "celery_task_duration{name=\"io_task\"}",
     "legendFormat": "{{name}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Success Rate by Worker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker_host, worker_type) (rate(celery_task_event{state=\"SUCCESS\"}[5m]))",
     "legendFormat": "{{worker_type}}@{{worker_host}}"
    }
   ]
  },
  {
   "title": "Failure Rate by Worker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker_host, worker_type) (rate(celery_task_event{state=\"FAILURE\"}[5m]))",
     "legendFormat": "{{worker_type}}@{{worker_host}}"
    }
   ]
  }
 ]
}