{
 "title": "Gunicorn",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Percentage of 2xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(gunicorn_request_status{status=~\"2..\"}) / sum(gunicorn_requests) * 100",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "Percentage of 3xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(gunicorn_request_status{status=~\"3..\"}) / sum(gunicorn_requests) * 100",
     "legendFormat": "3XX"
    }
   ]
  },
  {
   "title": "Percentage of 4xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(gunicorn_request_status{status=~\"4..\"}) / sum(gunicorn_requests) * 100",
     "legendFormat": "4XX"
    }
   ]
  },
  {
   "title": "Percentage of 5xx response codes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(gunicorn_request_status{status=~\"5..\"}) / sum(gunicorn_requests) * 100",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(gunicorn_requests[5m])" }
   ]
  },
  {
   "title": "Logged critical",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "api_gunicorn_log_critical" }
   ]
  },
  {
   "title": "Logged exception",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "api_gunicorn_log_exception" }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gunicorn_request_duration_sum / gunicorn_request_duration_count"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "gunicorn_request_duration{quantile=\"0.5\"}",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "gunicorn_request_duration{quantile=\"0.9\"}",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "gunicorn_request_duration{quantile=\"0.99\"}",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}