version: '3.4'

x-logging:
  &fluentd-logging
  driver: fluentd
  options:
    fluentd-address: localhost:24224

services:

  rabbitmq:
    depends_on:
      - fluentd
    logging: *fluentd-logging

  postgres:
    depends_on:
      - fluentd
    logging: *fluentd-logging

  cpu_worker:
    depends_on:
      - fluentd
    logging: *fluentd-logging

  io_worker:
    depends_on:
      - fluentd
    logging: *fluentd-logging

  api:
    depends_on:
      - fluentd
    logging: *fluentd-logging

  traefik:
    depends_on:
      - fluentd
    logging: *fluentd-logging

#  jaeger:
#    depends_on:
#      - fluentd
#    logging: *fluentd-logging
#
#  flower:
#    depends_on:
#      - fluentd
#    logging: *fluentd-logging
#
#  statsd:
#    depends_on:
#      - fluentd
#    logging: *fluentd-logging
#
#  prometheus:
#    depends_on:
#      - fluentd
#    logging: *fluentd-logging
#
#  grafana:
#    depends_on:
#      - fluentd
#    logging: *fluentd-logging

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    healthcheck:
      test: curl -sf http://localhost:5601
    labels:
      traefik.enable: true
      traefik.http.routers.kibana.rule: Host(`kibana.localhost`)

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      discovery.type: single-node
    healthcheck:
      test: curl -sf http://localhost:9200
    labels:
      traefik.enable: true
      traefik.http.routers.elasticsearch.rule: Host(`elasticsearch.localhost`)

  fluentd:
    build: ./../infra/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"