scrape_configs:

  - job_name: "statsd"
    static_configs:
      - targets: ["statsd:9102"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
